browser_deb_pkgs:
    - dbus-x11
    - firefox
    - gdebi
    - libcurl3
    - libgconf2-4
    - libnss3-1d
    - libxss1
    - xdg-utils
    - xvfb

# Debian packages we host in S3 to ensure correct browser version
# Both Chrome and FireFox update their apt repos with the latest version,
# which often causes spurious acceptance test failures.
browser_s3_deb_pkgs:
    - { name: "google-chrome-stable_55.0.2883.87-1_amd64.deb", url: "https://s3.amazonaws.com/vagrant.testeng.edx.org/google-chrome-stable_55.0.2883.87-1_amd64.deb" }

# Firefox
firefox_version: version 45.*

# ChromeDriver
chromedriver_version: 2.27
chromedriver_url: "http://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"

# PhantomJS
phantomjs_version: "phantomjs-1.9.8-linux-x86_64"
phantomjs_tarfile: "{{ phantomjs_version }}.tar.bz2"
phantomjs_url: "https://bitbucket.org/ariya/phantomjs/downloads/{{ phantomjs_tarfile }}"

browser_xvfb_display: ":1"
